name: 'Wait for TCP Service'
description: 'Wait for a TCP port to become reachable'
author: 'kula.app'

branding:
  icon: 'clock'
  color: 'blue'

inputs:
  host:
    description: 'The host of the service'
    required: true
  port:
    description: 'The port of the service'
    required: true
  timeout:
    description: 'The timeout in seconds for the service to be ready'
    required: false
    default: '20'
  interval:
    description: 'The interval in seconds to check if the service is ready'
    required: false
    default: '1'
  wait-indefinitely:
    description: 'If true, the action will wait indefinitely for the service to be ready'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
