name: Test Redis

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Redis
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.4.3
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Redis
        uses: ./
        with:
          type: redis
          host: redis
          port: 6379
          timeout: 300

  test-timeout:
    name: Test Redis - Timeout
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Redis
        id: wait-for-redis
        uses: ./
        continue-on-error: true
        with:
          type: redis
          host: redis
          port: 6379
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-redis.outcome != 'failure'
        run: exit 1
