name: Test MongoDB

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  universal-reachable:
    name: Test MongoDB (Universal, Reachable)
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:8.2.7
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for MongoDB
        uses: ./
        with:
          type: mongodb
          host: mongodb
          port: 27017
          timeout: 300

  universal-timeout:
    name: Test MongoDB (Universal, Timeout)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for MongoDB
        id: wait-for-mongodb
        uses: ./
        continue-on-error: true
        with:
          type: mongodb
          host: mongodb
          port: 27017
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-mongodb.outcome != 'failure'
        run: exit 1

  dedicated-reachable:
    name: Test MongoDB (Dedicated, Reachable)
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:8.2.7
        ports:
          - 27017:27017
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Wait for MongoDB
        uses: ./mongodb
        with:
          host: localhost
          port: 27017
          timeout: 300

  dedicated-timeout:
    name: Test MongoDB (Dedicated, Timeout)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Wait for MongoDB
        id: wait-for-mongodb
        uses: ./mongodb
        continue-on-error: true
        with:
          host: localhost
          port: 27017
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-mongodb.outcome != 'failure'
        run: exit 1
