name: Test Android Emulator

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Android Emulator
    runs-on: ubuntu-latest
    services:
      android-emulator:
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64-no-metrics:30.1.2
        ports:
          - 5555:5555
        options: >-
          --device /dev/kvm
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Android Emulator
        uses: ./
        with:
          type: android-emulator
          host: android-emulator
          port: 5555
          timeout: 300

  test-timeout:
    name: Test Android Emulator - Timeout
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Android Emulator
        id: wait-for-android-emulator
        uses: ./
        continue-on-error: true
        with:
          type: android-emulator
          host: android-emulator
          port: 5555
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-android-emulator.outcome != 'failure'
        run: exit 1
